<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<meta http-equiv="Pragma" content="no-cache">
		<meta http-equiv="Cache-Control" content="no-cache">

		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript" charset="utf-8" async="async"></script>
		<link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
	</head>

	<body>

<script>
//window.resizeBy(520,480);
</script>


<style>
* { margin: 0px; padding: 0px; font-size:9pt; }
body { overflow: hidden; }
ul { list-style: none; margin: 0px; font-size:0px; }
a:hover { opacity: 0.85; }

div#game-wrapper { width:100vw; height:100vh; position:relative; background:#f9f9f9; margin-left: auto; margin-right: auto;
		background-image: url("/res/images/bg/home/pipo-battlebg003.jpg");
		background-repeat: no-repeat;
		background-size:auto 100%;
		background-position:center top;
}

#game-header { height:50px; background:#ffc107; margin-bottom: 5px; }
#game-content-panel { overflow: hidden; }



/** ------------- menu ---------------- */
/** ------------- menu ---------------- */
div.game-menu { position: absolute; right:0px; bottom: 0px;}
div.game-menu ul { text-align:right; }
div.game-menu ul li { display: inline-block; margin:2px; }
div.game-menu ul li a { display: block; width:53px;height:50px; text-align:center; text-decoration: none; background:#17a2b8; color:#f9f9f9; }
div.game-menu ul li a span { line-height:20px; }
div.game-menu ul li a span.fa { line-height:30px; font-size:20px; }
div.game-menu ul li a.menu { background:#fd7e14;}

div#game-menu { right:1px; }
div#game-menu-panel { display: none; }
/** ------------- menu ---------------- */

ul.game-block-list li a { display: block; height:60px; line-height:60px; margin: 5px 0px; background: #fd7e14; color:#fafafa; }
ul.game-block-list li a span.fa { padding:0px 10px; font-size:20px; }

</style>
