<script>
var presto = class Presto {
	// コンテンツのロード
	static load(target, url, params) {
		console.log(`load content. url:${url}, target:${target}`);

		this.loading(target);
		$.ajax({ type: "GET", url: url, data: params, timeout: 3000 }).done(function(data){
			console.log(data);
			$(target).html(data);
		}).fail(function(data){
			console.log('error',data);
			$(target).html(data);
		}).always(function(data){
			console.log('always...');
		});

		//$(target).load(url, params);
		//this.loadingCompleted(target);
	}


	// ローディング効果の表示
	static loading(target){
		if(! $(`${target} div.presto-loading`).length ){
			$(target).prepend("<div class='presto-loading' style='text-align:center; width:100%; height:90%;'><img src='/res/icons/loading.colorful.gif'></div>");
		}
	}

	// ローディング効果の終了
	static loadingCompleted(target){
		$(`${target} div.presto-loading`).remove();
	}
}


$(function(){
	// リンクを押下した際
	$("body").on("click", "a.presto-get", function(event){
		// リンクの直接遷移を無効化
		event.preventDefault();

		console.log(`<${$(this).text()}> is clicked ! `);

		let url = $(this).attr("href");
		let target = $(this).attr("p-target");
		let parameter = $(this).attr("p-param");

		if(! $(this).attr("href")) {
			console.log(`no action to do !`);
			return false;
		}

		if(target){
			return presto.load(target, url, parameter);
		}else{
			return presto.load("#game-content-panel", url, parameter);
		}
	});
});
</script>