<style>
div.character-panel {}
div.character-panel div { float: left; margin:2px;}
</style>

<div class="character-panel">
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
	<div>{@ echo character()->image(mt_rand(1,250), 85, 2) }</div>
</div>
