<style>
#game-header .player-status { float: left; margin-left:10px; }
#game-header .player-asset { float: right; margin-right:10px; text-align:right; }

#game-header .player-status div, #game-header .player-asset div { height:16px; line-height:16px; margin-top:1px; font-size:8pt; }


#game-menu-panel { background:#f9f9f9; }
</style>

<script>
$(function(){
	$("div.game-menu ul li a").click(function(){
		if($(this).attr("href")!=""){
			$('div#game-menu-panel').hide();
		}
	});
});
</script>


<div id="game-wrapper">
	<div id="game-header">
		<div style="float: left;">{@ echo character()->image(1) } </div>

		<div class="player-status">
			<div>Lv: 101</div>
			<div>Exp: 121202121</div>
			<div>Home Base: 1-7</div>
		</div>

		<div class="player-asset">
			<div>Stone: 100</div>
			<div>Gold: 1000</div>
			<div>Coin: 1000000</div>
		</div>
	</div>


	<div id="game-content-panel">@include('html/pages/game/home/index')</div>


	<div id="game-menu-panel" class="game-menu">
		<ul>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>HELP</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-cogs"></span><br><span>設定</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-university"></span><br><span>遊び方</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>課金</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>SHOP</span></a></li>

			<li><a class="presto-get" href="/game/common/character/index/"><span class="fa fa-user-shield"></span><br><span>図鑑</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-mask"></span><br><span>アサシン</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>SURVIVOR</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>DEFENDER</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>HERO</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>基地</span></a></li>

			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>素材</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>EQUIP</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>ITEM</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-angle-down"></span><br><span>STORE</span></a></li>

			<li><a class="presto-get inactive" href=""><span class="fa fa-chess-rook"></span><br><span>EVENT</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-gift"></span><br><span>SHOP</span></a></li>
			<li><a class="presto-get" href="/game/quest/top/"><span class="fa fa-map"></span><br><span>QUEST</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-chess-knight"></span><br><span>DECK</span></a></li>
			<li><a class="presto-get inactive" href=""><span class="fa fa-chess"></span><br><span>CRAFT</span></a></li>

			<li><a class="presto-get" href="/game/home/"><span class="fa fa-chess-queen"></span><br><span>HOME</span></a></li>
			<li><a class="presto-get menu" href=""><span class="fa fa-bars"></span><br><span>MENU</span></a></li>
		</ul>
	</div>

	<div id="game-menu" class="game-menu">
		<ul>
			<li><a class="presto-get menu" href="" onclick="$('div#game-menu-panel').toggle();"><span class="fa fa-bars"></span><br><span>MENU</span></a></li>
		</ul>
	</div>
</div>
