

<style>
* { margin: 0px; padding: 0px; font-size:9pt; }
ul { list-style: none; margin: 0px; font-size:0px; }
#game-wrapper { width:400px; height:100vh; position:relative; background:#f9f9f9; margin-left: auto; margin-right: auto; }
#game-header { display:block; height:50px; background:#eee; }
#game-content { overflow: hidden; }

/** ------------- menu ---------------- */
/** ------------- menu ---------------- */
div.game-menu { position: absolute; right:0px; bottom: 0px; background:#eee; }
div.game-menu ul { text-align:left; }
div.game-menu ul li { display: inline-block; margin:2px; }
div.game-menu ul li a { display: block; width:53px; text-align:center; height:50px; text-decoration: none; background:#17a2b8; color:#f9f9f9; }
div.game-menu ul li a span { line-height:20px; }
div.game-menu ul li a span.fa { line-height:30px; font-size:20px; }
div.game-menu ul li a.menu { background:#fd7e14;}

div#game-menu { right:1px; }
div#game-menu-panel { display: none; width:100%; }
/** ------------- menu ---------------- */

</style>

<div id="game-wrapper">
	<div id="game-header">
		<div style="float: left;">
			<div style="width: 50px; height:50px; border:solid 3px #777;border-radius: 0px 10px 10px 0px;">ICON</div>
		</div>

		<div style="float: left; margin-left:10px;">
			<div>Lv</div>
			<div>Exp</div>
		</div>

		<div style="float: right;">
			<div>Stone</div>
			<div>Coin</div>
		</div>
	</div>


	<div id="game-content"></div>


	<div id="game-menu-panel" class="game-menu">
		<ul>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>HELP</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>課金</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>SHOP</span></a></li>
		</ul>

		<ul>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>SURVIVOR</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>DEFENDER</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>HERO</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>基地</span></a></li>
		</ul>

		<ul>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>-</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>素材</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>EQUIP</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>ITEM</span></a></li>
			<li><a href=""><span class="fa fa-angle-down"></span><br><span>STORE</span></a></li>
		</ul>

		<ul class="main">
			<li><a href=""><span class="fa fa-bell"></span><br><span>EVENT</span></a></li>
			<li><a href=""><span class="fa fa-gift"></span><br><span>SHOP</span></a></li>
			<li><a href="/game/quest/top/"><span class="fa fa-map"></span><br><span>QUEST</span></a></li>
			<li><a href=""><span class="fa fa-chess-knight"></span><br><span>DECK</span></a></li>
			<li><a href=""><span class="fa fa-chess"></span><br><span>CRAFT</span></a></li>
			<li><a href="/game/home/"><span class="fa fa-chess-rook"></span><br><span>HOME</span></a></li>
		</ul>
	</div>

	<div id="game-menu" class="game-menu">
		<ul>
			<li><a href="" onclick="$('div#game-menu-panel').toggle();" class=menu><span class="fa fa-bars"></span><br><span>MENU</span></a></li>
		</ul>
	</div>
</div>