@include('html/partials/admin/header')
@include('html/partials/presto.js')
@include('html/partials/presto.css')

<body>
	@include('html/partials/admin/nav')
	<div class="container-fluid">
			<div class='row thrones-content'>@content</div>
	</div>

	<div class="thrones-box thrones-padding thrones-footer">@include('html/partials/admin/footer')</div>
	@include('html/partials/admin/modal')
</body>
</html>