<style>
div.game-character {background: #f9f9f9; border: solid 1px #fd7e14; border-radius:5px; margin-bottom:5px; padding:5px; opacity: 0.85; }
div.game-character:hover {background: #fd7e14; border: solid 1px #f9f9f9; }
div.game-character:hover * { color: #f9f9f9; }
</style>

<div id="game-character-list">
	<div class="game-hidden-scrollbar" style="">
	@foreach ($characters as $character)
	<div class="game-character">
		<div style="float: left; margin-right:10px;">{@ echo character()->image($character["character_original_id"], 50) }</div>
		<div style="float: left;">
			original : {{ $character["character_original_id"] }},
			{{ $character["name"] }}<br>
			serial : {{ $character["serial_id"] }},
			type : {{ $character["type"] }},
			rank : {{ $character["rank_min"] }} ~ {{ $character["rank_max"] }}
		</div>
		<br style="clear: both;">
	</div>
	@endforeach

	{@ html()->pager()->css("presto-get")->target("div#game-character-list")->render($count) }
	</div>

</div>