<style type="text/css">
.fa { margin-right: 5px; }
* { font-size: 9pt; }

body { background:#f9f9f9; }

/* テーブル行数 */
table.table-counter {counter-reset: row-counter;}
table.table-counter thead tr, table.table-counter tbody tr { position: relative; }
table.table-counter thead tr:before { position: relative; padding: 10px; display: block; bottom: 0; content: "#" }
table.table-counter tbody tr:before { position: relative; padding: 10px; display: block; bottom: 0; counter-increment: row-counter; content: "#"counter(row-counter); }

th, td { white-space: nowrap; }


a.thrones-logo { padding: 0px 20px; font-weight: bold; }
div.thrones-box { background: #fff; border: solid 1px #eee; box-shadow: 5px 5px 5px rgba(0,0,0,0.2); margin-bottom: 10px; }
div.thrones-padding { padding:10px; }
div.thrones-content { margin-bottom:120px; }
div.thrones-footer { position: fixed; width:100vw; bottom:0px; margin-bottom:0px; }


ul.pagination li { margin: 1px; }


/* ------------------ loadder ------------------ */
/* ------------------ loadder ------------------ */
.loader,
.loader:after {
  border-radius: 50%;
  width: 10em;
  height: 10em;
}
.loader {
  margin: 60px auto;
  font-size: 10px;
  position: relative;
  text-indent: -9999em;
  border-top: 1.1em solid rgba(0,128,128, 0.2);
  border-right: 1.1em solid rgba(0,128,128, 0.2);
  border-bottom: 1.1em solid rgba(0,128,128, 0.2);
  border-left: 1.1em solid #008080;
  -webkit-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
  -webkit-animation: load8 1.1s infinite linear;
  animation: load8 1.1s infinite linear;
}
@-webkit-keyframes load8 {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes load8 {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
/* ------------------ loadder ------------------ */

</style>