<table class="table table-hover  table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Host</th>
      <th>Database</th>
      <th>Character</th>
    </tr>
  </thead>

  <tbody>
    @foreach ($databases as $conn=>$db)
    <tr>
      <td><a href="/admin/database/tables/?conn={{ $conn }}"><span class="fa fa-database"></span>{{ $conn }}</a></td>
      <td>{{ $db["host"] }}</td>
      <td>{{ $db["db"] }}</td>
      <td>{{ $db["character"] }}</td>
    </tr>
    @endforeach
  </tbody>
</table>
