<div class="col-md-5">
	<ul class="list-unstyled">
	@foreach ($directories as $sub)
		<li><a href='/admin/resource/index/?root={{$root}}&path={{ $sub }}'><span class='fa fa-folder'></span>{{ $sub }}</a></li>
	@endforeach
	</ul>
</div>

<div class="col-md-7">
	@if ($root=="public")
		<div class=row>
		@foreach ($files as $sub)
			@if (preg_match("/\.[png|jpg|gif|jpeg]/", $sub["name"]))
			<div class=" col-md-6"><div class="card mb-3">
				<img class="card-img-top" src="/res{{$sub["name"]}}" alt="{{$sub["name"]}}">
				<div class="card-body">
					<a href="#" class="btn btn-primary">{{$sub["name"]}}</a>
				</div>
			</div></div>
			@endif
		@endforeach
		</div>

	@else
		<ul class="list-unstyled">
		@foreach ($files as $sub)
			<li><a href='/admin/resource/view/?root={{$root}}&path={{ $sub["name"] }}' class='load-to-modal presto-get' p-target="div.modal-body" data-toggle="modal" data-target="#modal">
				<span class="fa fa-file"></span>{{ $sub["name"] }}</a>
				<span style="margin-left: 5px;">{@ echo util()->unit()->auto($sub["size"]) }</span>
			</li>
		@endforeach
		</ul>
	@endif
</div>

{@ // directory()->tree(path("app/resources")) }