<div class="col-md-5">
	<ul class="list-unstyled">
	@foreach ($directories as $sub)
		<li><a href='/admin/resource/index/?root={{$root}}&path={{ $sub }}'><span class='fa fa-folder'></span>{{ $sub }}</a></li>
	@endforeach
	</ul>
</div>

<div class="col-md-7">
	<ul class="list-unstyled">
	@foreach ($files as $sub)
		<li><a href='/admin/resource/view/?root={{$root}}&path={{ $sub }}' class='load-to-modal presto-get' p-target="div.modal-body" data-toggle="modal" data-target="#modal">
			<span class="fa @if (pathinfo($sub, PATHINFO_EXTENSION)=='csv') fa-file-csv @else fa-file @endif "></span>{{ $sub }}</a></li>
	@endforeach
	</ul>
</div>

{@ // directory()->tree(path("app/resources")) }