<div class="row">
	<div class="col-md-11">
		<di class="table-responsive form-group">
			<form id="presto-search-form"><table class='table'>
				<input type=hidden name=parameters[type] id=search-type value="like">
				<tbody>
					<tr>
						@foreach ($fields as $col=>$field)
						<?php $val = isset($parameters['conditions'][$field]) ? $parameters['conditions'][$field] : "";?>
						<th><textarea class="form-control" name="parameters[conditions][{{ $field }}]" placeholder="{{ $field }}" style="min-height: 50px; min-width: 80px;">{{ $val }}</textarea></th>
						@endforeach
					</tr>
				</tbody>
			</table></form>
		</di>
	</div>
	<div class="col-md-1 text-right">
		<style>ul.presto-search-button li { margin-bottom: 2px; }</style>
		<ul class="presto-search-button list-unstyled">
			<li><a href="{@ echo html()->pager()->baseurl() }" class="btn btn-sm btn-block btn-info presto-post" p-target="div.modal-body" p-form="#presto-search-form" p-param='{type: "like"}'>類似検索</a></li>
			<li><a href="{@ echo html()->pager()->baseurl() }" class="btn btn-sm btn-block btn-success presto-post" p-target="div.modal-body" p-form="#presto-search-form" p-param='{type: "strict"}'>厳密検索</a></li>
			<li><a href="{@ echo html()->pager()->baseurl() }" class="btn btn-sm btn-block btn-warning presto-post" p-target="div.modal-body" p-param='{type: "reset"}'>RESET</a></li>
		</ul>
	</div>
</div>

<div class="table-responsive" style="max-height:60vh; overflow: scroll; margin:10px 0px;">

@if ($extension=="csv")
	<table class='table table-counter table-striped table-bordered table-hover'>
		<thead class="thead-light">
			<tr>@foreach ($fields as $col=>$field) <th>{{ $field }}</th> @endforeach</tr>
		</thead>

		<tbody>
		@foreach ($rows as $line=>$row)
			<tr>@foreach ($row as $key=>$val) <td>{{ $val }}</td> @endforeach</tr>
		@endforeach
		</tbody>
	</table>

@elseif ($extension=="json")
	@foreach ($rows as $line=>$row)
		{@ echo debugbar()->toHtml($row) }
	@endforeach
@endif
</div>

<div>{@ html()->pager()->css("presto-get")->target("div.modal-body")->render($count) }</div>
