<div class="col-md-12">

<table class="table table-counter table-hover table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Comment</th>
			<th>Rows</th>
			<th>Auto_increment</th>
			<th>Create_time</th>
			<th>Update_time</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach ($tables as $table)
		<tr>
			<td><a href="/admin/database/datas/?conn={{ $conn }}&table={{ $table['Name'] }}" class="load-to-modal" data-toggle="modal" data-target="#modal"><span class='fa fa-table'></span>{{ $table["Name"] }}</a></td>
			<td>{{ $table["Comment"] }}</td>
			<td>{{ $table["Rows"] }}</td>
			<td>{{ $table["Auto_increment"] }}</td>
			<td>{{ $table["Create_time"] }}</td>
			<td>{{ $table["Update_time"] }}</td>
			<td>
				<form action="">
					<div class="input-group">
						<label class="input-group-btn"><span class="btn btn-primary">File<input type="file" name=csvfile value="" style="display: none;" onchange="$('#{{$table['Name']}}').val($(this).val());"></span></label>
						<input type="text" id="{{$table['Name']}}" class="form-control" readonly="">
					</div>
				</form>
			</td>
			<td><a class="btn btn-sm btn-warning">UPLOAD</a></td>
			<td><a href="" class="btn btn-sm btn-info">DOWNLOAD</a></td>
		</tr>
		@endforeach
	</tbody>
</table>


</div>