<style>
ul.game-quest-list li a { display: block; height:60px; line-height:60px; margin: 5px; background: #fd7e14; color:#fafafa; }
ul.game-quest-list li a span.fa { padding:0px 10px; font-size:20px; }
</style>

<ul class="game-quest-list">
	<li><a href="/game/quest/main/battle?area_id={{$area['id']}}"><span class="fa fa-area"></span><span>バトル</span></a></li>
	<li><a href="/game/quest/main/battle?area_id={{$area['id']}}&is_boss=1"><span class="fa fa-area"></span><span>ボスバトル</span></a></li>
</ul>