@include('html/pages/game/quest/main/js/animate.js')
@include('html/pages/game/quest/main/js/battle.js')

<style>
/* ************** animation *************** */
div#mask-opening {
    position: absolute; width:100%; height:100%; opacity: 1; z-index:1;
    background: url('/res/images/effect/opening.png') no-repeat;background-size: 100% 3000px;
    /* animation: opening 1.2s steps(10) forwards; */
}
@keyframes opening {
    100% { background-position: 0px -3000px; opacity:0; }
}

div.battle-effect-1 {
    background: url('/res/images/effect/opening.png') no-repeat;background-size: 160px 100%;
    animation: opening 1.2s steps(5) forwards;
}
@keyframes battle-effect-1 {
    100% { background-position: -800px; opacity:0; }
}
/* ************** animation *************** */

div#battle-round {
    position: absolute; top:50%; left:50%; transform: translate(-50%,-50%);
    border-radius: 50%;
    box-sizing: border-box;
    width:100%; text-align: center;
    height:60px; line-height:50px;
    color: #dc3545; font-size:14pt; font-weight: bold;
    animation: round-effect .3s infinite;
}
@keyframes round-effect {
    100% { opacity: 0.7; font-size:16pt; }
}


.game-battle-actor { position: relative; margin-bottom: 5px; }
.game-battle-actor .mask, .game-battle-actor .mask-skill-effect { position:absolute; width:100%; height:100%; opacity: 0.4; }
.game-battle-actor .mask-damage {
    display:none; position:absolute; top:-3px; background:#dc3545; padding:0px 15px; color:#f9f9f9; font-weight:bold; z-index:1; opacity: 0.9;
    border-radius: 5px;
    font-size:10pt;
    animation: damage 0.6s infinite;
}
@keyframes damage {  100% {opacity:0.6;} }

.game-gauge { background: #fd7e14; padding:1px; margin-bottom:2px; }
.game-gauge .bar-base { background: #888; width:100px; height:10px; }
.game-gauge .bar-base .bar-val { overflow:hidden;background:#28a745; width:100px; height:10px; line-height:10px; font-size:4pt; color:#f9f9f9; }
.game-gauge .bar-base .bar-val span { height:10px; line-height:10px; font-size:4pt; color:#f9f9f9;}

#game-battle-log { position:fixed; bottom:0px; padding:5px; width:100vw; height: 400px; background:#f9f9f9; border: solid 5px #ccc; overflow-y: scroll; opacity:0.8; }
/* scroll barを非表示 */
#game-battle-log::-webkit-scrollbar{ display:none; }
#game-battle-log span.log-line { display: block; margin-bottom:2px; background:#6c757d; color:#f9f9f9; }
#game-battle-log span.round { background:#fd7e14; }
#game-battle-log span.turn { background:#ffc107; padding-left:5px; }
#game-battle-log span.actor { background:#17a2b8; padding-left:10px; }
#game-battle-log span.action { background:#888; padding-left:15px; }

</style>

<div id="game-actor-list" style="position: relative;">
	<div id="mask-opening"></div>
	<div id="battle-round"></div>

	<div style="float: left;">
		@foreach ($Battle->AllyDeck->Actors as $key=>$Actor)
		<div id="game-actor-{{$Actor->actor_id}}" class="game-battle-actor">
			<div class="mask"></div>
			<div class="mask-skill-effect"></div>
			<div class="mask-damage" style="right:-20px;"></div>

			<div style="float: left;">{@ echo character()->image($Actor->actor_id) }</div>
			<div style="float: left; margin-left:5px;">
				<!-- ------------------- gauge ------------------ -->
				<div class="game-gauge hp-gauge"><div class="bar-base"><div class="bar-val hp-bar">HP:<span class="hp-text"><?php echo $Actor->baseHp();?></span> /<span class="hp-base-text"><?php echo $Actor->baseHp();?></span></div></div></div>
				<div class="game-gauge mp-gauge"><div class="bar-base"><div class="bar-val mp-bar" style="background:#fd7e14;">MP:<span class="mp-text"><?php echo $Actor->baseMp();?></span> /<span class="mp-base-text"><?php echo $Actor->baseMp();?></span></div></div></div>
				<div class="game-gauge bp-gauge"><div class="bar-base"><div class="bar-val ap-bar" style="background:#17a2b8;">AP:<span class="ap-text"><?php echo $Actor->baseAp();?></span> /<span class="ap-base-text"><?php echo $Actor->baseAp();?></span></div></div></div>
				<!-- ------------------- gauge ------------------ -->
			</div>
			<br style="clear: both;">
		</div>
		@endforeach
	</div>

	<div style="float: right; text-align: right;">
		@foreach ($Battle->OppenentDeck->Actors as $key=>$Actor)
		<div id="game-actor-{{$Actor->actor_id}}" class="game-battle-actor">
			<div class="mask"></div>
			<div class="mask-skill-effect"></div>
			<div class="mask-damage" style="left:-20px;"></div>

			<div style="float: right;">{@ echo character()->image($Actor->actor_id) }</div>
			<div style="float: right; margin-right:5px;">
				<!-- ------------------- gauge ------------------ -->
				<div class="game-gauge hp-gauge"><div class="bar-base"><div class="bar-val hp-bar">HP:<span class="hp-text"><?php echo $Actor->baseHp();?></span> /<span class="hp-base-text"><?php echo $Actor->baseHp();?></span></div></div></div>
				<div class="game-gauge mp-gauge"><div class="bar-base"><div class="bar-val mp-bar" style="background:#fd7e14;">MP:<span class="mp-text"><?php echo $Actor->baseMp();?></span> /<span class="mp-base-text"><?php echo $Actor->baseMp();?></span></div></div></div>
				<div class="game-gauge bp-gauge"><div class="bar-base"><div class="bar-val ap-bar" style="background:#17a2b8;">AP:<span class="ap-text"><?php echo $Actor->baseAp();?></span> /<span class="ap-base-text"><?php echo $Actor->baseAp();?></span></div></div></div>
				<!-- ------------------- gauge ------------------ -->
			</div>
			<br style="clear: both;">
		</div>
		@endforeach
	</div>
	<br style="clear: both;">
</div>

<div class="text-right" style="position:absolute; z-index: 2;width:100%;"><a href="javascript:void(0);" class="btn btn-success" onclick="battle.play();">バトル演出</a></div>
<div id="game-battle-log"></div>

<!--
<?php echo ($Battle->LogManage->toJson()); ?>
 -->