<style>
ul.game-quest-list li a { display: block; height:60px; line-height:60px; margin: 5px; background: #fd7e14; color:#fafafa; }
ul.game-quest-list li a span.fa { padding:0px 10px; font-size:20px; }
</style>

<ul class="game-quest-list">
	@foreach($maps as $map)
	<li><a href="/game/quest/main/areas?map_id={{$map['id']}}"><span class="fa fa-map"></span><span>{{$map['name']}}</span></a></li>
	@endforeach
</ul>