
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6" style="border: solid 1px #bbb; background:#eee;">
          <table class="table">
            <tr>
              <td colspan=2 align=center><b>LOGIN FORM</b></td>
            </tr>

            <tr>
              <th>Email</th>
              <td><input type="text" name="email" id="email" class="form-control"></td>
            </tr>

            <tr>
              <th>Password</th>
              <td><input type="text" name="password" id="password" class="form-control"></td>
            </tr>

            <tr>
              <td align=left><a class="btn btn-info" href="/admin/auth/google/">Login With Google</a></td>
              <td align=right><a class="btn btn-warning" href="javascript:void(0);">LOGIN</a></td>
            </tr>
          </table>
        </div>
    </div>
</div>
