<?php

$result = database("player_shard_01")->update("test", ["name"=>"player#update", "modified"=>date("Y-m-d H:i:s")], ["id"=>10]);
exit;
for ($i=1; $i<=10; $i++){
    $row = [];
    $row["name"] = "player." . date("ymd-His");
    $row["created"] = date("Y-m-d H:i:s");
    $row["modified"] = date("Y-m-d H:i:s");
    $result = database("player")->insert("test", $row);

    echo "<pre>";
    var_dump($result);
    echo "</pre>";
}

?>

{@ // var_dump(csv()->find(path("app/resources/csvs/master_character.csv"), ["category"=>1, "type"=>2])) }

{@ // var_dump(csv()->getBody(path("app/resources/csvs/master_character.csv"))) }

<pre>
<?php
timelines("before query !");
timelines("query completed !");

$cond = [];
$cond['A'] = 1;
$cond['B'] = 2;
$cond['C'] = 3;
list($where, $binds) = where($cond);
var_dump([$where, $binds, $cond]);


$cond = [];
$cond['A'] = 1;
$cond['or']['B'] = 2;
$cond['or']['C'] = 3;
list($where, $binds) = where($cond);
var_dump([$where, $binds, $cond]);

$cond = [];
$cond['A']["in"] = [1,2,3,10,22,33];
$cond['or'][0]['B'] = 2;
$cond['or'][0]['C']["in"] = [1,2,5,5,5,5,5,5,5];
$cond['or'][0]['D'] = 4;
$cond['or'][1]['B'] = 2;
$cond['or'][1]['D'] = 4;

list($where, $binds) = where($cond);
var_dump([$where, $binds, $cond]);


// bug!!!!!!!!!!!!!!!
$cond = [];
$cond['A']["in"] = [1,2,3,10,22,33];
$cond['or']['B'] = 2;
$cond['or'][0]['C']["in"] = [1,2,5,5,5,5,5,5,5];
$cond['or'][0]['D'] = 4;
list($where, $binds) = where($cond);
var_dump([$where, $binds, $cond]);

?>


</pre>



<pre>

<?php
$rows = [
    ["A"=>1, "B"=>1, "C"=>10, "D"=>4],
    ["A"=>2, "B"=>1, "C"=>11, "D"=>4],
    ["A"=>3, "B"=>2, "C"=>20, "D"=>4],
    ["A"=>4, "B"=>2, "C"=>21, "D"=>4],
    ["A"=>5, "B"=>3, "C"=>30, "D"=>4],
    ["A"=>6, "B"=>3, "C"=>31, "D"=>4],
];

$conds = [
    [
        "A"=>1,
    ],

    [
        "A"=>[">="=> 4],
    ],

    [
        "A"=>[">="=> 3],
        "B"=>["in"=>[1,2]],
    ],

    [
        "A"=>["in"=> [1,2,3,4,6]],
        "or"=>["B"=>2, "C"=>31],
    ],

];


foreach ($conds as $cond)
{
    $result = collection($rows)->where($cond);
    var_dump($result->all());
}

?>


Player Decks
{@ html()->table($playerDecks) }

player characters
{@ var_dump(database("player")->select("player_character", ["conditions"=>["id"=>["in"=> ['2',2,3]]]])) }
-------------------------------------

{@ html()->table(database("admin")->select("admin", ["conditions"=>["id"=>1]])) }

{@ html()->table(database("admin")->select("admin", ["fields"=>["id", "name"]])) }


Count : {@ echo database("admin")->count("admin", ["conditions"=>["id"=>1]]) }

Sum : {@ var_dump(database("admin")->sum("admin", ["fields"=>["id", "role_id"]])) }

Paging :
{@ html()->table(database("admin")->paging("admin")->all()) }

</pre>