<div class="col-md-4">
  <span class="d-block p-2 rounded text-white bg-info">リンク</span>
  <ul class="list-unstyled">
    <li><a href="/admin/resource/index/"><span class="fa fa-file"></span>Resource一覧</a></li>
    <li><a href="/admin/database/index/"><span class="fa fa-database"></span>DB一覧</a></li>

    <li><a href="/admin/top/test/"><span class="fa fa-file"></span>テスト用</a></li>
  </ul>
</div>


<?php
$kpis = [
    "総ユーザ数",
    "新規ユーザ数",
    "DAU",
    "MAU",
    "売上金額",
    "消費金額",
    "未消費金額",
    "課金者数",
    "課金率",
    "課金平均額",
    "新規課金者数",

    "3日継続ユーザ数",
    "5日継続ユーザ数",
    "7日継続ユーザ数",
    "14日継続ユーザ数",
    "30日継続ユーザ数",

    "週間2日以上継続ユーザ数",
    "週間3日以上継続ユーザ数",
    "週間4日以上継続ユーザ数",
    "週間5日以上継続ユーザ数",
    "週間6日以上継続ユーザ数",

    "月間5日以上継続ユーザ数",
    "月間10日以上継続ユーザ数",
    "月間15日以上継続ユーザ数",
    "月間20日以上継続ユーザ数",
    "月間25日以上継続ユーザ数",
];

?>


<div class="col-md-8">
  <span class="d-block p-2 rounded text-white bg-info">KPI</span>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th></th>
        <th>今日</th>
        <th>昨日</th>
        <th>今週</th>
        <th>先週</th>
        <th>今月 / 昨年</th>
        <th>先月 / 昨年</th>
      </tr>

    </thead>
    <tbody>
      @foreach ($kpis as $title)
      <tr>
        <th>{{ $title }}</th>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
