<div class="col-md-5 col-sm-8" style="border: solid 1px #bbb; background:#eee;">
  <form method="POST" action="/admin/auth/login/">
    <table class="table">
      <tbody>
        <tr>
          <td align="center"><b>LOGIN FORM</b></td>
        </tr>

        <tr>
          <td>Email</td><td><input type="text" name="email" id="email" class="form-control"></td>
        </tr>
        <tr>
          <td>Password</td><td><input type="password" name="password" id="password" class="form-control"></td>
        </tr>

        <tr>
          <td colspan=2>
            <a class="btn btn-warning btn-block" href="javascript:void(0);" onclick="window.open('/game/top/index/', 'Game', 'width=400,height=800,scrollbars=none,resizable=none');">LOGIN</a>
          </td>
        </tr>
      </tbody>
    </table>
  </form>
</div>