<div class="col-md-4">
	<!--
	<iframe src="/game/top/index/" width=100% height=800 style="border:solid 5px #17a2b8;"></iframe>
	 -->
	<iframe id="game-panel" src="" width=100% height=800 style="border:solid 5px #17a2b8;"></iframe>
</div>


<div class="col-md-8">
	<div class=" thrones-box thrones-padding">
		<span class="d-block p-2 rounded text-white bg-info"><span class="fa fa-info-circle"></span>GAME LOGIN</span>
		<form method="POST" action="/admin/auth/login/">
			<table class="table">
				<tbody>
					<tr>
						<td>LOGIN ID</td>
						<td><input type="text" name="loginid" id="loginid" class="form-control"></td>
						<td></td>
					</tr>

					<tr>
						<td>LOGIN PW</td>
						<td><input type="text" name="loginpw" id="loginpw" class="form-control"></td>
						<td align=right>
							<a class="btn btn-warning" href="javascript:void(0);" onclick="$('iframe#game-panel').attr('src', '/game/top/index/');">GAME LOGIN</a>
							<a class="btn btn-danger" href="javascript:void(0);" onclick="window.open('/game/top/index/', 'Game', 'width=400,height=800,scrollbars=none,resizable=none');">GAME LOGIN(新窓)</a>
						</td>
					</tr>

					<tr>
						<td><a class="btn btn-info presto-get" p-target="#admin-dummy-list" href="/admin/debug/game/account/">ダミーアカウント一覧</a></td>
						<td colspan=2>
							<div style="float: right;">
								<a class="btn btn-success presto-get" p-target="#admin-dummy-list" p-ref='{"count":{"el":"#admin-regist-count"}}' href="/admin/debug/game/regist/">ダミーアカウント作成</a>
							</div>
							<div style="float: right; margin-right:5px;">
								{@ html()->select()->tagid("admin-regist-count")->title("作成個数を選択")->append(" 個")->render("count", range(1,10) ) }
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>

	<div id="admin-dummy-list" style="position: relative;"></div>
</div>