<style>
ul.game-quest-list li a { display: block; height:60px; line-height:60px; margin: 5px; background: #fd7e14; color:#fafafa; }
ul.game-quest-list li a span.fa { padding:0px 10px; font-size:20px; }
</style>

<ul class="game-quest-list">
	<li><a href="/game/quest/main/"><span class="fa fa-map"></span><span>メインクエスト</span></a></li>
	<li><a href="/game/quest/main/"><span class="fa fa-map"></span><span>探索</span></a></li>
	<li><a href="/game/quest/main/"><span class="fa fa-map"></span><span>訓練所</span></a></li>
</ul>